//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlinikApp.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KlinikDBEntities : DbContext
    {
        public KlinikDBEntities()
            : base("name=KlinikDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cinsiyet> Cinsiyet { get; set; }
        public virtual DbSet<Hizmet> Hizmet { get; set; }
        public virtual DbSet<Personel> Personel { get; set; }
        public virtual DbSet<Pozisyon> Pozisyon { get; set; }
        public virtual DbSet<Randevu> Randevu { get; set; }
        public virtual DbSet<RDurum> RDurum { get; set; }
        public virtual DbSet<RSonuc> RSonuc { get; set; }
        public virtual DbSet<RSTur> RSTur { get; set; }
        public virtual DbSet<Hasta> Hasta { get; set; }
    }
}
