//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlinikApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Randevu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Randevu()
        {
            this.RSonuc = new HashSet<RSonuc>();
        }
    
        public int R_ID { get; set; }
        public Nullable<int> R_PERSONELID { get; set; }
        public Nullable<int> R_HASTAID { get; set; }
        public Nullable<int> R_HIZMETID { get; set; }
        public Nullable<byte> R_DURUMID { get; set; }
        public Nullable<System.DateTime> R_TARIH { get; set; }
        public string R_ACIKLAMA { get; set; }
    
        public virtual Hizmet Hizmet { get; set; }
        public virtual Personel Personel { get; set; }
        public virtual RDurum RDurum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSonuc> RSonuc { get; set; }
        public virtual Hasta Hasta { get; set; }
    }
}
