//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlinikApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSonuc
    {
        public int S_ID { get; set; }
        public Nullable<int> S_RANDEVUID { get; set; }
        public Nullable<byte> S_TURID { get; set; }
        public string S_ACIKLAMA { get; set; }
    
        public virtual Randevu Randevu { get; set; }
        public virtual RSTur RSTur { get; set; }
    }
}
